nelmio_api_doc:
    documentation:
        info:
            title: "Media Manager API"
            description: "This is the API documentation for the Media Manager service."
            version: "1.0.0"
        paths:
            /login:
                post:
                    tags: ["Authentication"]
                    summary: "Log in to get JWT token"
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: "Returns JWT token"
                        '401':
                            description: "Unauthorized"
            /logout:
                get:
                    tags: ["Authentication"]
                    summary: "Logout user"
                    responses:
                        '302':
                            description: "User logged out"

    areas:
        # List of areas to include in the documentation
        path_patterns: [ '^/api', '^/login', '^/logout' ]
