services:
  # Backend (Symfony)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./backend:/var/www/symfony
      - ./php.ini:/etc/phpINI/php.ini
    environment:
      - APP_ENV=dev
    networks:
      - app_network

  # Database
  database:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3307:3306"

  # Nginx for Symfony
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www/symfony
    depends_on:
      - backend
    networks:
      - app_network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src   # Mounts your local 'src' folder to the Docker container's 'src' folder
      - ./frontend/public:/app/public   # Mounts public folder for hot reload as well
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures hot-reload works inside Docker
    networks:
      - app_network

  # Mailer
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app_network

  # ClamAV
  clamav:
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310"
    networks:
      - app_network
    volumes:
      - clamav_data:/var/lib/clamav/


  worker:
    image: rg-media-manager-backend:latest
    container_name: symfony_worker
    command: php bin/console messenger:consume async --time-limit=3600
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www/symfony
    networks:
      - app_network

  # RabbitMQ for Symfony Messenger
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"   # RabbitMQ connection port
#      - "15672:15672" # RabbitMQ management UI
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data:
  clamav_data:
